crud/Models/ErrorViewModel.cs
namespace Tutorial.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

crud/Models/Student.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Tutorial.Models
{
    public class Student
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage ="กรุณาป้อนชื่อนักเรียน")]
        [DisplayName("ชื่อนักเรียน")]
        public required string Name { get; set; }

        [DisplayName("คะแนนสอบ")]
        [Range(0,100,ErrorMessage ="กรุณาป้อนคะแนนสอบในช่วง 0-100")]
        public int Score { get; set; }
    }
}

crud/Controllers/HomeController.cs
using Tutorial.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Tutorial.Controllers
{
    public class homeController : Controller
    {
        private readonly ILogger<homeController> _logger;

        public homeController(ILogger<homeController> logger)
        {
            _logger = logger;
        }

        public IActionResult index()
        {
            return View();
        }

        public IActionResult privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

crud/Controllers/StudentController.cs
using Tutorial.Data;
using Tutorial.Models;
using Microsoft.AspNetCore.Mvc;

namespace Tutorial.Controllers
{
    public class studentController : Controller
    {
        private readonly ApplicationDBContext _db;

        public studentController(ApplicationDBContext db)
        {
            _db = db;
        }

        public IActionResult index()
        {
            IEnumerable <Student> allStudent = _db.Students;
            return View(allStudent);
        }
        // GET METHOD
        public IActionResult create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult create(Student obj)
        {
            if (ModelState.IsValid)
            {
                _db.Students.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("index");
            }
            return View(obj);
        }

        public IActionResult edit(int? id)
        {
            if (id==null || id==0)
            {
                return NotFound();
            }
            var obj = _db.Students.Find(id);
            if (obj==null)
            {
                return NotFound();
            }
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult edit(Student obj)
        {
            if (ModelState.IsValid)
            {
                _db.Students.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("index");
            }
            return View(obj);
        }

        public IActionResult delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //ค้นหาข้อมูล
            var obj = _db.Students.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Students.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

crud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Tutorial.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="student" asp-action="index">ระบบจัดการคะแนนสอบ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="student" asp-action="index">หน้าแรก</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="student" asp-action="create">บันทึกข้อมูล</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2567 - test
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

crud/Views/home/index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">test</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

crud/Views/student/create.cshtml
@model Student;
@{
    ViewData["Title"] = "บันทึกข้อมูล";
}

<h1 class="text-center">บันทึกคะแนนสอบ</h1>
<form method="POST" asp-controller="student" asp-action="create">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input type="text" asp-for="Name" class="form-control"/>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Score"></label>
        <input type="number" asp-for="Score" class="form-control"/>
        <span asp-validation-for="Score" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary my-2">บันทึก</button>
</form>

crud/Views/student/edit.cshtml
@model Student;
@{
    ViewData["Title"] = "แก้ไขข้อมูล";
}

<h1 class="text-center">แก้ไขข้อมูล</h1>
<form method="POST" asp-controller="student" asp-action="edit">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input type="text" asp-for="Name" class="form-control"/>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Score"></label>
        <input type="number" asp-for="Score" class="form-control"/>
        <span asp-validation-for="Score" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary my-2">อัพเดต</button>
</form>

crud/Views/student/index.cshtml
@model IEnumerable<Student>;
@{
    ViewData["Title"] = "หน้าแรก";
}

@if (Model.Count()>0)
{
    <h1 class="text-center">คะแนนสอบวิชาคอมพิวเตอร์</h1>
    <table class="table ">
        <thead>
            <tr>
            <th>รหัสนักเรียน</th>
                <th>ชื่อนักเรียน</th>
                <th>คะแนนสอบ</th>
                <th>แก้ไข</th>
                <th>ลบ</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var student in Model)
            {
                    <tr>
                        <td>@student.Id</td>
                        <td>@student.Name</td>
                        <td>@student.Score</td>
                        <td>
                            <a class="btn btn-warning" 
                    asp-controller="student"
                    asp-action="edit"
                    asp-route-id="@student.Id">แก้ไข</a>
                        </td>
                        <td><a class="btn btn-danger"
                    asp-controller="student"
                    asp-action="delete"
                    asp-route-id="@student.Id"
                    onclick="return confirm('คุณต้องการลบ @student.Name หรือไม่ ?')"
                    >ลบ</a>
                        </td>
                    </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-secondary">ไม่มีข้อมูลนักเรียนในระบบ</div>
}